### ISSUE TITLE
Boolector (**request**)

### ISSUE THREAD

**Issue by weaversa** [GaloisInc/what4-solvers#13]
boolector had been included in the docker containers for Cryptol and SAW. It does outperform the currently available solvers on some problems.

**Comment by RyanGlScott** [comment]
Yes, good idea. I've created a new [`snapshot-20220131`](https://github.com/GaloisInc/what4-solvers/releases/tag/snapshot-20220131) tag that includes a bindist with Boolector 3.2.2.
