### ISSUE TITLE
Get CVC4 building on Windows

### ISSUE THREAD

**Issue by atomb** [GaloisInc/what4-solvers#4]
Currently, CI builds CVC4 on Linux and macOS but downloads a pre-built binary for Windows. It should be possible to get it to build directly.

**Comment by RyanGlScott** [comment]
This proves somewhat tricky, since CVC4 only supports cross-compiling Windows binaries rather than building it natively on Windows. There is some ongoing work to allow native Windows CVC5 builds (see cvc5/cvc5#7512), so if that is successful, we could consider backporting these changes to CVC4.
