### ISSUE TITLE
Suspicious warning when building CVC4 on `macos-14`

### ISSUE THREAD

**Issue by RyanGlScott** [GaloisInc/what4-solvers#53]
When building CVC4 on `macos-14` (which uses ARM64), a very suspicious-looking warning is generated:

```
============== WARNING ====================
The script guessed that this machine is 32 bit.
If antlr should be built as 64 bit (i.e. -m64),
please rerun the script as
MACHINE_TYPE="x86_64" ./get-antlr3.4
```

The build still succeeds (and the resulting CVC4 binary passes tests), but I can't help but wonder if some part of the code is being misinterpreted as 32 bits instead of 64. The following patch might suffice to fix this:

```diff
diff --git a/contrib/get-antlr-3.4 b/contrib/get-antlr-3.4
index 45dc86583..4daba2810 100755
--- a/contrib/get-antlr-3.4
+++ b/contrib/get-antlr-3.4
@@ -43,6 +43,8 @@ install_bin "$ANTLR_HOME_DIR/bin/antlr3"
 setup_dep \
   "https://www.antlr3.org/download/C/libantlr3c-3.4.tar.gz" \
   "$ANTLR_HOME_DIR/libantlr3c-3.4"
+# Use a more up-to-date config.guess script
+cp "${CONFIG_GUESS_SCRIPT}" "$ANTLR_HOME_DIR/libantlr3c-3.4/config.guess"
 cd "$ANTLR_HOME_DIR/libantlr3c-3.4"
 
 # Make antlr3debughandlers.c empty to avoid unreferenced symbols

```

**Comment by sauclovian-g** [comment]
Some time back when Apple was trying to move from 32-bit to 64-bit x86, there were assorted kinds of weirdness and lossage that could happen by mixing the environments, and it was consequently sometimes necessarily to explicitly pick a size. I don't think this is an issue any more (in fact, I don't think you can build 32-bit binaries any more) so my inclination is that as long as antlr seems to build and run ok we don't need to worry about it.

I can look further into what the MACHINE_TYPE setting actually does in antlr's build system if you think it's worthwhile.

**Comment by RyanGlScott** [comment]
One thing that I forgot to mention in my original post (but probably should have) is that you can also trigger this warning when building on AArch64 Linux, not just macOS. (We don't yet have AArch64 Linux builds, but [we might someday](https://github.com/GaloisInc/what4-solvers/issues/50).) As such, this isn't exclusively a macOS issue.

> I can look further into what the MACHINE_TYPE setting actually does in antlr's build system if you think it's worthwhile.

I ended up needing to research this myself when building CVC4 for AArch64 Linux, so I have a pretty good sense for what `MACHINE_TYPE` does: it's used to pick different flags for varying architectures in the build script. CVC4's build script is rather old and was seemingly written without AArch64 in mind, so we already have to patch various parts of the script to be aware of the `aarch64` `MACHINE_TYPE`: see [this patch](https://github.com/GaloisInc/what4-solvers/blob/982ebbb55d64ada02fd6192a09591935b76f92e6/patches/cvc4-antlr-check-aarch64.patch).

That being said, I think that patch is incomplete, as the "script guessed that this machine is 32 bit" warning still occurs. This ends up being for a separate reason, however: CVC4 compiles `antlr-3.4` as part of its build, and the `config.guess` file that `antlr-3.4` uses is also rather old (dating back to 2009). As such, it is not aware of `aarch64-darwin-*` or `aarch64-linux-*`, and attempting to run `config.guess` on either OS will yield a `MACHINE_TYPE` that looks like `unknown-darwin` or `unknown-linux`. Because neither of these equal `x86-64`, [this warning](https://github.com/CVC4/CVC4-archived/blob/40eac7f0529176bcc8464d6c4c8804fbde628c2b/contrib/get-antlr-3.4#L96-L101) will be triggered.

You're right in that this is ultimately not that big of a deal for AArch64 macOS, since the rest of the script works out OK even with the miscategorized `MACHINE_TYPE`. It _is_ a big deal for AArch64 Linux, however, as picking build flags intended to 32-bit Linux causes an actual build failure later. I ended up needing the patch from https://github.com/GaloisInc/what4-solvers/issues/53#issue-2644910505 in addition to some other patches in order to fix this. I'll follow up on https://github.com/GaloisInc/what4-solvers/issues/53 to describe the other patches that I needed to make this work.

**Comment by sauclovian-g** [comment]
...because of course x86_64 is the only 64-bit platform out there :-|

Anyway, may as well merge the patches, I think, unless you want to rework the configury more to make it somewhat closer to being sound.

**Comment by RyanGlScott** [comment]
I agree that we should merge the patches from https://github.com/GaloisInc/what4-solvers/issues/50#issuecomment-2467971470 (with some additional cleanup). I'll submit a PR.
